# Server settings.
server:
  rootPath: '/api/*'

#running environment
environment: dev

# scheduler configuration
scheduler:
  enabled: true

# JSON Web Token secret
auth:
  jwt_secret: "test"

# Database settings.
databases:
  middleware:
    driverClass: com.mysql.jdbc.Driver
    user: root
    password: middleware
    url: jdbc:mysql://localhost:3306/middleware

email-alert:
  host: localhost
  #port: 465
  transport-strategy: PLAIN # PLAIN | SSL | TLS
  #username: xxxx@objectedge.com
  #password: xxxx
  email-to: USER@objectedge.com
  email-from: noreply@objectedge.com

logging:
  level: INFO
  loggers:
      org.hibernate.engine.internal.StatisticalLoggingSessionEventListener: WARN
      com.objectedge: DEBUG
      com.<project>: DEBUG

occ:
  host: https://ccadmin-z1ma.oracleoutsourcing.com
  store_host: https://ccstore-z1ma.oracleoutsourcing.com
  assets_language: en
  timeout: 30
  admin:
    username: "USER@objectedge.com"
    password: ""
  agent:
    username: "USER@objectedge.com"
    password: ""
  adminUI:
    username: "USER@objectedge.com"
    password: ""
  agentUI:
    username: "USER@objectedge.com"
    password: ""
  application_id: ""
  application_secret: ""
  connection_type: APPLICATION | USER
  webhook_secret: Asdf124#124



